@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam linetype ortho

entity "Student" as Student {
  *id: Integer <<GENERATED>>
  --
  first_name: text
  last_name: text
  dadname: text
  telephone: text
  telegram: text
  mail: text
  git:text
}

@enduml