@startuml
'https://plantuml.com/class-diagram
abstract class StudentBase {
    -id: Integer
    -telephone: String
    -telegram: String
    -mail: String
    -git: String
    __
    +{static}valid_name?(String): Boolean
    +{static}valid_profile_name?(String): Boolean
    +{static}valid_telephone?(String): Boolean
    +{static}valid_email?(String): Boolean
    -initialize(Hash)
    +has_git?(): Boolean
    +has_contacts?(): Boolean
    +valid?(): Boolean
    +get_contact(): String
    __
    +id
    +git
    #telephone
    #telegram
    #mail
    __
    #id
    #git=(String)
    #telephone=(String)
    #telegram=(String)
    #mail=(String)

}
class StudentShort extends StudentBase {
    -short_fio: String
    -contact: Hash
    --
    +{static}from_student(Student): StudentShort
    +initialize(id,info_short): StudentShort
    +to_s(): String
    --
    +short_fio:String
    +contact: Hash
    --
    -short_fio
    -contact
}
class Student extends StudentBase{
    -last_name: String
    -first_name: String
    -dadname: String
    --
    +{static}from_json(String): Student
    +initialize(String, String, String, Hash)
    +set_contacts(Hash)
    +short_info(): String
    +info_short():String
    +to_s(): String
    +to_json(): String
    --
    +telephone: String
    +telegram: String
    +mail: String
    +last_name: String
    +first_name: String
    +dadname: String
    __
    +id
    +git=(String)
    +telephone=(String)
    +telegram=(String)
    +mail=(String)
    +last_name=(String)
    +first_name=(String)
    +dadname=(String)
}

class DataTable{
    -table : Array
    -rows_count: Integer
    -cols_count: Integer
    __
    +initialize(Array)
    +get_item(Integer,Integer): Object
    __
    +rows_count: Integer
    +cols_count: Integer
    -table: Array
    __
    -rows_count
    -cols_count
    -table
}

struct main {
    +{static}read_from_txt(String): List<Student>
    +{static}write_to_txt(List<Student>,String): File
}
@enduml